In [4]:
import pandas as pd
df=pd.DataFrame({'Bob':['i liked it','im alone'],
                 'Nam':['you are a boy','did they sleep?'],
                 'Khánh':['1','2']},
                index=['1','2'])
df

          Bob              Nam Khánh
1  i liked it    you are a boy     1
2    im alone  did they sleep?     2

In [6]:
test=pd.Series([1,2,3,4,5],index=['Meo','Cho','lon','Ga','Bo'])
test

Meo    1
Cho    2
lon    3
Ga     4
Bo     5
dtype: int64

In [8]:
reviews=pd.read_csv('/content/supermarket_sales - Sheet1.csv')
reviews

      Invoice ID Branch  ... gross income Rating
0    750-67-8428      A  ...      26.1415    9.1
1    226-31-3081      C  ...       3.8200    9.6
2    631-41-3108      A  ...      16.2155    7.4
3    123-19-1176      A  ...      23.2880    8.4
4    373-73-7910      A  ...      30.2085    5.3
..           ...    ...  ...          ...    ...
995  233-67-5758      C  ...       2.0175    6.2
996  303-96-2227      B  ...      48.6900    4.4
997  727-02-1313      A  ...       1.5920    7.7
998  347-56-2442      A  ...       3.2910    4.1
999  849-09-3807      A  ...      30.9190    6.6

[1000 rows x 17 columns]

In [17]:
reviews.iloc[899:930,5]

899        Food and beverages
900    Electronic accessories
901        Home and lifestyle
902         Health and beauty
903        Food and beverages
904         Health and beauty
905        Home and lifestyle
906         Health and beauty
907         Health and beauty
908        Food and beverages
909        Home and lifestyle
910        Food and beverages
911    Electronic accessories
912        Home and lifestyle
913       Fashion accessories
914        Food and beverages
915    Electronic accessories
916         Sports and travel
917       Fashion accessories
918        Home and lifestyle
919    Electronic accessories
920        Home and lifestyle
921        Home and lifestyle
922        Home and lifestyle
923         Sports and travel
924         Sports and travel
925    Electronic accessories
926         Sports and travel
927         Health and beauty
928    Electronic accessories
929         Sports and travel
Name: Product line, dtype: object

In [18]:
reviews.City=='Yangon'

0       True
1      False
2       True
3       True
4       True
       ...
995    False
996    False
997     True
998     True
999     True
Name: City, Length: 1000, dtype: bool

In [22]:
reviews.loc[(reviews.City!='Naypyitaw')&(reviews.Quantity>8)]

      Invoice ID Branch  ... gross income Rating
13   252-56-2699      A  ...      21.5950    8.2
14   829-34-3910      A  ...      35.6900    5.7
29   848-62-7243      A  ...      11.2005    7.4
31   149-71-6266      B  ...      35.1315    4.5
37   272-65-1806      A  ...      27.3960    4.7
..           ...    ...  ...          ...    ...
970  746-04-1077      B  ...      42.3150    9.0
982  139-32-4183      A  ...      43.8660    7.4
991  602-16-6955      B  ...      38.3000    6.0
993  690-01-6631      B  ...       8.7450    6.6
996  303-96-2227      B  ...      48.6900    4.4

[139 rows x 17 columns]

In [33]:
reviews.loc[reviews.Branch.isin(['A', 'C'])]

      Invoice ID Branch  ... gross income Rating
0    750-67-8428      A  ...      26.1415    9.1
1    226-31-3081      C  ...       3.8200    9.6
2    631-41-3108      A  ...      16.2155    7.4
3    123-19-1176      A  ...      23.2880    8.4
4    373-73-7910      A  ...      30.2085    5.3
..           ...    ...  ...          ...    ...
994  652-49-6720      C  ...       3.0475    5.9
995  233-67-5758      C  ...       2.0175    6.2
997  727-02-1313      A  ...       1.5920    7.7
998  347-56-2442      A  ...       3.2910    4.1
999  849-09-3807      A  ...      30.9190    6.6

[668 rows x 17 columns]

In [ ]:
review.doc[review['Product line'].isin]]

In [36]:
reviews.City.describe()

count       1000
unique         3
top       Yangon
freq         340
Name: City, dtype: object

In [37]:
reviews.City.describe

<bound method NDFrame.describe of 0         Yangon
1      Naypyitaw
2         Yangon
3         Yangon
4         Yangon
         ...
995    Naypyitaw
996     Mandalay
997       Yangon
998       Yangon
999       Yangon
Name: City, Length: 1000, dtype: object>

In [41]:
reviews['Product line'].describe()

count                    1000
unique                      6
top       Fashion accessories
freq                      178
Name: Product line, dtype: object

In [43]:
reviews.Quantity.describe()

count    1000.000000
mean        5.510000
std         2.923431
min         1.000000
25%         3.000000
50%         5.000000
75%         8.000000
max        10.000000
Name: Quantity, dtype: float64

In [44]:
reviews.dtypes

Invoice ID                  object
Branch                      object
City                        object
Customer type               object
Gender                      object
Product line                object
Unit price                 float64
Quantity                     int64
Tax 5%                     float64
Total                      float64
Date                        object
Time                        object
Payment                     object
cogs                       float64
gross margin percentage    float64
gross income               float64
Rating                     float64
dtype: object

In [45]:
type(reviews)

pandas.core.frame.DataFrame

In [46]:
reviews.describe()

        Unit price     Quantity  ...  gross income      Rating
count  1000.000000  1000.000000  ...   1000.000000  1000.00000
mean     55.672130     5.510000  ...     15.379369     6.97270
std      26.494628     2.923431  ...     11.708825     1.71858
min      10.080000     1.000000  ...      0.508500     4.00000
25%      32.875000     3.000000  ...      5.924875     5.50000
50%      55.230000     5.000000  ...     12.088000     7.00000
75%      77.935000     8.000000  ...     22.445250     8.50000
max      99.960000    10.000000  ...     49.650000    10.00000

[8 rows x 8 columns]

In [47]:
reviews.City.unique()

array(['Yangon', 'Naypyitaw', 'Mandalay'], dtype=object)

In [48]:
reviews.City.value_counts()

Yangon       340
Mandalay     332
Naypyitaw    328
Name: City, dtype: int64

In [49]:
reviews['Product line'].value_counts()

Fashion accessories       178
Food and beverages        174
Electronic accessories    170
Sports and travel         166
Home and lifestyle        160
Health and beauty         152
Name: Product line, dtype: int64

In [50]:
quantity_mean=reviews.Quantity.mean()
print('mean',quantity_mean)

mean 5.51

In [51]:
Total_mean=reviews.Total.mean()
print('mean',Total_mean)

mean 322.96674900000005

In [53]:
gross_margin_percentage=reviews['gross margin percentage'].mean()
print('mean',gross_margin_percentage)

mean 4.761904762000062