## Install Pandas

In [4]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.1.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.1)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.19.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

## Import Pandas

In [5]:
import pandas as pd

## Load data into Pandas

### From CSV files

In [11]:
df = pd.read_csv('/content/pokemon_data.csv')

FileNotFoundError: ignored

In [9]:
df.head()

NameError: ignored

### From Excel files

In [ ]:
df_excel = pd.read_excel('/content/pokemon_data.xlsx')

### From text files

In [ ]:
df_txt = pd.read_csv('/content/pokemon_data.txt', delimiter='\t')

## Read data

### Read only a few first rows of a dataframe

In [ ]:
df.head(3)

   #       Name Type 1  Type 2  ...  Speed  Generation  Legendary  Total
0  1  Bulbasaur  Grass  Poison  ...     45           1      False    318
1  2    Ivysaur  Grass  Poison  ...     60           1      False    405
2  3   Venusaur  Grass  Poison  ...     80           1      False    525

[3 rows x 13 columns]

In [ ]:
df_excel.head(3)

   #       Name Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
0  1  Bulbasaur  Grass  Poison  ...       65     45           1      False
1  2    Ivysaur  Grass  Poison  ...       80     60           1      False
2  3   Venusaur  Grass  Poison  ...      100     80           1      False

[3 rows x 12 columns]

In [ ]:
df_txt.head(3)

   #       Name Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
0  1  Bulbasaur  Grass  Poison  ...       65     45           1      False
1  2    Ivysaur  Grass  Poison  ...       80     60           1      False
2  3   Venusaur  Grass  Poison  ...      100     80           1      False

[3 rows x 12 columns]

### Read a few last rows of a dataframe

In [ ]:
df.tail(4)

       #                 Name   Type 1  ... Generation  Legendary  Total
796  719  DiancieMega Diancie     Rock  ...          6       True    700
797  720  HoopaHoopa Confined  Psychic  ...          6       True    600
798  720   HoopaHoopa Unbound  Psychic  ...          6       True    680
799  721            Volcanion     Fire  ...          6       True    600

[4 rows x 13 columns]

### Read a few random rows

In [ ]:
df.sample(7)

       #      Name  Type 1    Type 2  ...  Speed  Generation  Legendary  Total
755  685  Slurpuff   Fairy       NaN  ...     72           6      False    480
503  453  Croagunk  Poison  Fighting  ...     50           4      False    300
60    55   Golduck   Water       NaN  ...     85           1      False    500
294  271    Lombre   Water     Grass  ...     50           3      False    340
287  264   Linoone  Normal       NaN  ...    100           3      False    420
707  644    Zekrom  Dragon  Electric  ...     90           5       True    680
427  385   Jirachi   Steel   Psychic  ...    100           3       True    600

[7 rows x 13 columns]

### Read unique values of a column

In [ ]:
df.shape

(800, 13)

In [ ]:
df['Type 1'].unique()

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

### Read headers of a dataframe

In [ ]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary', 'Total'],
      dtype='object')

### Read a specific column

In [ ]:
df['Name']

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [ ]:
df['Name'][2:6]

2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
5               Charmeleon
Name: Name, dtype: object

In [ ]:
df[['Name']][2:6]

In [ ]:
df['Defense'][2:11]

2      83
3     123
4      43
5      58
6      78
7     111
8      78
9      65
10     80
Name: Defense, dtype: int64

### Read some columns

In [ ]:
df[['Name', 'HP', 'Type 2']]

                      Name  HP  Type 2
0                Bulbasaur  45  Poison
1                  Ivysaur  60  Poison
2                 Venusaur  80  Poison
3    VenusaurMega Venusaur  80  Poison
4               Charmander  39     NaN
..                     ...  ..     ...
795                Diancie  50   Fairy
796    DiancieMega Diancie  50   Fairy
797    HoopaHoopa Confined  80   Ghost
798     HoopaHoopa Unbound  80    Dark
799              Volcanion  80   Water

[800 rows x 3 columns]

In [ ]:
df['Name']

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

### Read a specific row

In [ ]:
df.iloc[1]

#                   2
Name          Ivysaur
Type 1          Grass
Type 2         Poison
HP                 60
Attack             62
Defense            63
Sp. Atk            80
Sp. Def            80
Speed              60
Generation          1
Legendary       False
Total             405
Name: 1, dtype: object

### Read a few rows

In [ ]:
df.iloc[1:4]

   #                   Name Type 1  Type 2  ...  Speed  Generation  Legendary  Total
1  2                Ivysaur  Grass  Poison  ...     60           1      False    405
2  3               Venusaur  Grass  Poison  ...     80           1      False    525
3  3  VenusaurMega Venusaur  Grass  Poison  ...     80           1      False    625

[3 rows x 13 columns]

In [ ]:
df[1:4]

   #                   Name Type 1  Type 2  ...  Speed  Generation  Legendary  Total
1  2                Ivysaur  Grass  Poison  ...     60           1      False    405
2  3               Venusaur  Grass  Poison  ...     80           1      False    525
3  3  VenusaurMega Venusaur  Grass  Poison  ...     80           1      False    625

[3 rows x 13 columns]

### Read a specific cell

In [ ]:
df.iloc[1,1]

'Ivysaur'

### Read a few cells

In [ ]:
df.iloc[1:4, 1:3]

                    Name Type 1
1                Ivysaur  Grass
2               Venusaur  Grass
3  VenusaurMega Venusaur  Grass

In [ ]:
df[['Name', 'Type 1']][1:4]

                    Name Type 1
1                Ivysaur  Grass
2               Venusaur  Grass
3  VenusaurMega Venusaur  Grass

## Describe data

In [ ]:
df.describe()

                #          HP      Attack  ...       Speed  Generation      Total
count  800.000000  800.000000  800.000000  ...  800.000000   800.00000  800.00000
mean   362.813750   69.258750   79.001250  ...   68.277500     3.32375  435.10250
std    208.343798   25.534669   32.457366  ...   29.060474     1.66129  119.96304
min      1.000000    1.000000    5.000000  ...    5.000000     1.00000  180.00000
25%    184.750000   50.000000   55.000000  ...   45.000000     2.00000  330.00000
50%    364.500000   65.000000   75.000000  ...   65.000000     3.00000  450.00000
75%    539.250000   80.000000  100.000000  ...   90.000000     5.00000  515.00000
max    721.000000  255.000000  190.000000  ...  180.000000     6.00000  780.00000

[8 rows x 9 columns]

## Sort data

### By 1 column

In [ ]:
df.sort_values(by='Name', ascending=False)

       #                     Name   Type 1  ... Generation  Legendary  Total
794  718         Zygarde50% Forme   Dragon  ...          6       True    600
695  634                 Zweilous     Dark  ...          5      False    420
46    41                    Zubat   Poison  ...          1      False    245
631  570                    Zorua     Dark  ...          5      False    330
632  571                  Zoroark     Dark  ...          5      False    510
..   ...                      ...      ...  ...        ...        ...    ...
393  359          AbsolMega Absol     Dark  ...          3      False    565
392  359                    Absol     Dark  ...          3      False    465
68    63                     Abra  Psychic  ...          1      False    310
511  460  AbomasnowMega Abomasnow    Grass  ...          4      False    594
510  460                Abomasnow    Grass  ...          4      False    494

[800 rows x 13 columns]

### By many columns

In [ ]:
df.sort_values(by=['Type 1', 'HP'], ascending=[True, False])[:10]

       #                     Name Type 1  ... Generation  Legendary  Total
520  469                  Yanmega    Bug  ...          4      False    515
698  637                Volcarona    Bug  ...          5      False    550
231  214                Heracross    Bug  ...          2      False    500
232  214  HeracrossMega Heracross    Bug  ...          2      False    600
678  617                 Accelgor    Bug  ...          5      False    495
734  666                 Vivillon    Bug  ...          6      False    411
447  402               Kricketune    Bug  ...          4      False    384
220  205               Forretress    Bug  ...          2      False    465
602  542                 Leavanny    Bug  ...          5      False    500
717  649                 Genesect    Bug  ...          5      False    600

[10 rows x 13 columns]

## Make changes to the data

### Add columns

In [ ]:
df.head()

   #                   Name Type 1  Type 2  ...  Speed  Generation  Legendary  Total
0  1              Bulbasaur  Grass  Poison  ...     45           1      False    318
1  2                Ivysaur  Grass  Poison  ...     60           1      False    405
2  3               Venusaur  Grass  Poison  ...     80           1      False    525
3  3  VenusaurMega Venusaur  Grass  Poison  ...     80           1      False    625
4  4             Charmander   Fire     NaN  ...     65           1      False    309

[5 rows x 13 columns]

In [ ]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary', 'Total'],
      dtype='object')

In [ ]:
df['TOTAL'] = df['HP'] + df['Attack']

In [ ]:
df.head()

   #                   Name Type 1  Type 2  ...  Generation  Legendary  Total  TOTAL
0  1              Bulbasaur  Grass  Poison  ...           1      False    318     94
1  2                Ivysaur  Grass  Poison  ...           1      False    405    122
2  3               Venusaur  Grass  Poison  ...           1      False    525    162
3  3  VenusaurMega Venusaur  Grass  Poison  ...           1      False    625    180
4  4             Charmander   Fire     NaN  ...           1      False    309     91

[5 rows x 14 columns]

In [ ]:
45+49

94

### Drop columns

In [ ]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary', 'Total', 'TOTAL'],
      dtype='object')

In [ ]:
df.drop(columns=['TOTAL'], axis = 1, inplace=True)

KeyError: ignored

In [ ]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary', 'Total'],
      dtype='object')

### Replace a specific value in a column

In [ ]:
df.head()

In [ ]:
df['Type 1'].unique()

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

In [ ]:
df['Name'].unique()

array(['Bulbasaur', 'Ivysaur', 'Venusaur', 'VenusaurMega Venusaur',
       'Charmander', 'Charmeleon', 'Charizard',
       'CharizardMega Charizard X', 'CharizardMega Charizard Y',
       'Squirtle', 'Wartortle', 'Blastoise', 'BlastoiseMega Blastoise',
       'Caterpie', 'Metapod', 'Butterfree', 'Weedle', 'Kakuna',
       'Beedrill', 'BeedrillMega Beedrill', 'Pidgey', 'Pidgeotto',
       'Pidgeot', 'PidgeotMega Pidgeot', 'Rattata', 'Raticate', 'Spearow',
       'Fearow', 'Ekans', 'Arbok', 'Pikachu', 'Raichu', 'Sandshrew',
       'Sandslash', 'Nidoran (Female)', 'Nidorina', 'Nidoqueen',
       'Nidoran (Male)', 'Nidorino', 'Nidoking', 'Clefairy', 'Clefable',
       'Vulpix', 'Ninetales', 'Jigglypuff', 'Wigglytuff', 'Zubat',
       'Golbat', 'Oddish', 'Gloom', 'Vileplume', 'Paras', 'Parasect',
       'Venonat', 'Venomoth', 'Diglett', 'Dugtrio', 'Meowth', 'Persian',
       'Psyduck', 'Golduck', 'Mankey', 'Primeape', 'Growlithe',
       'Arcanine', 'Poliwag', 'Poliwhirl', 'Poliwrath', 'Abra', 'Kadabra',
       'Alakazam', 'AlakazamMega Alakazam', 'Machop', 'Machoke',
       'Machamp', 'Bellsprout', 'Weepinbell', 'Victreebel', 'Tentacool',
       'Tentacruel', 'Geodude', 'Graveler', 'Golem', 'Ponyta', 'Rapidash',
       'Slowpoke', 'Slowbro', 'SlowbroMega Slowbro', 'Magnemite',
       'Magneton', "Farfetch'd", 'Doduo', 'Dodrio', 'Seel', 'Dewgong',
       'Grimer', 'Muk', 'Shellder', 'Cloyster', 'Gastly', 'Haunter',
       'Gengar', 'GengarMega Gengar', 'Onix', 'Drowzee', 'Hypno',
       'Krabby', 'Kingler', 'Voltorb', 'Electrode', 'Exeggcute',
       'Exeggutor', 'Cubone', 'Marowak', 'Hitmonlee', 'Hitmonchan',
       'Lickitung', 'Koffing', 'Weezing', 'Rhyhorn', 'Rhydon', 'Chansey',
       'Tangela', 'Kangaskhan', 'KangaskhanMega Kangaskhan', 'Horsea',
       'Seadra', 'Goldeen', 'Seaking', 'Staryu', 'Starmie', 'Mr. Mime',
       'Scyther', 'Jynx', 'Electabuzz', 'Magmar', 'Pinsir',
       'PinsirMega Pinsir', 'Tauros', 'Magikarp', 'Gyarados',
       'GyaradosMega Gyarados', 'Lapras', 'Ditto', 'Eevee', 'Vaporeon',
       'Jolteon', 'Flareon', 'Porygon', 'Omanyte', 'Omastar', 'Kabuto',
       'Kabutops', 'Aerodactyl', 'AerodactylMega Aerodactyl', 'Snorlax',
       'Articuno', 'Zapdos', 'Moltres', 'Dratini', 'Dragonair',
       'Dragonite', 'Mewtwo', 'MewtwoMega Mewtwo X',
       'MewtwoMega Mewtwo Y', 'Mew', 'Chikorita', 'Bayleef', 'Meganium',
       'Cyndaquil', 'Quilava', 'Typhlosion', 'Totodile', 'Croconaw',
       'Feraligatr', 'Sentret', 'Furret', 'Hoothoot', 'Noctowl', 'Ledyba',
       'Ledian', 'Spinarak', 'Ariados', 'Crobat', 'Chinchou', 'Lanturn',
       'Pichu', 'Cleffa', 'Igglybuff', 'Togepi', 'Togetic', 'Natu',
       'Xatu', 'Mareep', 'Flaaffy', 'Ampharos', 'AmpharosMega Ampharos',
       'Bellossom', 'Marill', 'Azumarill', 'Sudowoodo', 'Politoed',
       'Hoppip', 'Skiploom', 'Jumpluff', 'Aipom', 'Sunkern', 'Sunflora',
       'Yanma', 'Wooper', 'Quagsire', 'Espeon', 'Umbreon', 'Murkrow',
       'Slowking', 'Misdreavus', 'Unown', 'Wobbuffet', 'Girafarig',
       'Pineco', 'Forretress', 'Dunsparce', 'Gligar', 'Steelix',
       'SteelixMega Steelix', 'Snubbull', 'Granbull', 'Qwilfish',
       'Scizor', 'ScizorMega Scizor', 'Shuckle', 'Heracross',
       'HeracrossMega Heracross', 'Sneasel', 'Teddiursa', 'Ursaring',
       'Slugma', 'Magcargo', 'Swinub', 'Piloswine', 'Corsola', 'Remoraid',
       'Octillery', 'Delibird', 'Mantine', 'Skarmory', 'Houndour',
       'Houndoom', 'HoundoomMega Houndoom', 'Kingdra', 'Phanpy',
       'Donphan', 'Porygon2', 'Stantler', 'Smeargle', 'Tyrogue',
       'Hitmontop', 'Smoochum', 'Elekid', 'Magby', 'Miltank', 'Blissey',
       'Raikou', 'Entei', 'Suicune', 'Larvitar', 'Pupitar', 'Tyranitar',
       'TyranitarMega Tyranitar', 'Lugia', 'Ho-oh', 'Celebi', 'Treecko',
       'Grovyle', 'Sceptile', 'SceptileMega Sceptile', 'Torchic',
       'Combusken', 'Blaziken', 'BlazikenMega Blaziken', 'Mudkip',
       'Marshtomp', 'Swampert', 'SwampertMega Swampert', 'Poochyena',
       'Mightyena', 'Zigzagoon', 'Linoone', 'Wurmple', 'Silcoon',
       'Beautifly', 'Cascoon', 'Dustox', 'Lotad', 'Lombre', 'Ludicolo',
       'Seedot', 'Nuzleaf', 'Shiftry', 'Taillow', 'Swellow', 'Wingull',
       'Pelipper', 'Ralts', 'Kirlia', 'Gardevoir',
       'GardevoirMega Gardevoir', 'Surskit', 'Masquerain', 'Shroomish',
       'Breloom', 'Slakoth', 'Vigoroth', 'Slaking', 'Nincada', 'Ninjask',
       'Shedinja', 'Whismur', 'Loudred', 'Exploud', 'Makuhita',
       'Hariyama', 'Azurill', 'Nosepass', 'Skitty', 'Delcatty', 'Sableye',
       'SableyeMega Sableye', 'Mawile', 'MawileMega Mawile', 'Aron',
       'Lairon', 'Aggron', 'AggronMega Aggron', 'Meditite', 'Medicham',
       'MedichamMega Medicham', 'Electrike', 'Manectric',
       'ManectricMega Manectric', 'Plusle', 'Minun', 'Volbeat',
       'Illumise', 'Roselia', 'Gulpin', 'Swalot', 'Carvanha', 'Sharpedo',
       'SharpedoMega Sharpedo', 'Wailmer', 'Wailord', 'Numel', 'Camerupt',
       'CameruptMega Camerupt', 'Torkoal', 'Spoink', 'Grumpig', 'Spinda',
       'Trapinch', 'Vibrava', 'Flygon', 'Cacnea', 'Cacturne', 'Swablu',
       'Altaria', 'AltariaMega Altaria', 'Zangoose', 'Seviper',
       'Lunatone', 'Solrock', 'Barboach', 'Whiscash', 'Corphish',
       'Crawdaunt', 'Baltoy', 'Claydol', 'Lileep', 'Cradily', 'Anorith',
       'Armaldo', 'Feebas', 'Milotic', 'Castform', 'Kecleon', 'Shuppet',
       'Banette', 'BanetteMega Banette', 'Duskull', 'Dusclops', 'Tropius',
       'Chimecho', 'Absol', 'AbsolMega Absol', 'Wynaut', 'Snorunt',
       'Glalie', 'GlalieMega Glalie', 'Spheal', 'Sealeo', 'Walrein',
       'Clamperl', 'Huntail', 'Gorebyss', 'Relicanth', 'Luvdisc', 'Bagon',
       'Shelgon', 'Salamence', 'SalamenceMega Salamence', 'Beldum',
       'Metang', 'Metagross', 'MetagrossMega Metagross', 'Regirock',
       'Regice', 'Registeel', 'Latias', 'LatiasMega Latias', 'Latios',
       'LatiosMega Latios', 'Kyogre', 'KyogrePrimal Kyogre', 'Groudon',
       'GroudonPrimal Groudon', 'Rayquaza', 'RayquazaMega Rayquaza',
       'Jirachi', 'DeoxysNormal Forme', 'DeoxysAttack Forme',
       'DeoxysDefense Forme', 'DeoxysSpeed Forme', 'Turtwig', 'Grotle',
       'Torterra', 'Chimchar', 'Monferno', 'Infernape', 'Piplup',
       'Prinplup', 'Empoleon', 'Starly', 'Staravia', 'Staraptor',
       'Bidoof', 'Bibarel', 'Kricketot', 'Kricketune', 'Shinx', 'Luxio',
       'Luxray', 'Budew', 'Roserade', 'Cranidos', 'Rampardos', 'Shieldon',
       'Bastiodon', 'Burmy', 'WormadamPlant Cloak', 'WormadamSandy Cloak',
       'WormadamTrash Cloak', 'Mothim', 'Combee', 'Vespiquen',
       'Pachirisu', 'Buizel', 'Floatzel', 'Cherubi', 'Cherrim', 'Shellos',
       'Gastrodon', 'Ambipom', 'Drifloon', 'Drifblim', 'Buneary',
       'Lopunny', 'LopunnyMega Lopunny', 'Mismagius', 'Honchkrow',
       'Glameow', 'Purugly', 'Chingling', 'Stunky', 'Skuntank', 'Bronzor',
       'Bronzong', 'Bonsly', 'Mime Jr.', 'Happiny', 'Chatot', 'Spiritomb',
       'Gible', 'Gabite', 'Garchomp', 'GarchompMega Garchomp', 'Munchlax',
       'Riolu', 'Lucario', 'LucarioMega Lucario', 'Hippopotas',
       'Hippowdon', 'Skorupi', 'Drapion', 'Croagunk', 'Toxicroak',
       'Carnivine', 'Finneon', 'Lumineon', 'Mantyke', 'Snover',
       'Abomasnow', 'AbomasnowMega Abomasnow', 'Weavile', 'Magnezone',
       'Lickilicky', 'Rhyperior', 'Tangrowth', 'Electivire', 'Magmortar',
       'Togekiss', 'Yanmega', 'Leafeon', 'Glaceon', 'Gliscor',
       'Mamoswine', 'Porygon-Z', 'Gallade', 'GalladeMega Gallade',
       'Probopass', 'Dusknoir', 'Froslass', 'Rotom', 'RotomHeat Rotom',
       'RotomWash Rotom', 'RotomFrost Rotom', 'RotomFan Rotom',
       'RotomMow Rotom', 'Uxie', 'Mesprit', 'Azelf', 'Dialga', 'Palkia',
       'Heatran', 'Regigigas', 'GiratinaAltered Forme',
       'GiratinaOrigin Forme', 'Cresselia', 'Phione', 'Manaphy',
       'Darkrai', 'ShayminLand Forme', 'ShayminSky Forme', 'Arceus',
       'Victini', 'Snivy', 'Servine', 'Serperior', 'Tepig', 'Pignite',
       'Emboar', 'Oshawott', 'Dewott', 'Samurott', 'Patrat', 'Watchog',
       'Lillipup', 'Herdier', 'Stoutland', 'Purrloin', 'Liepard',
       'Pansage', 'Simisage', 'Pansear', 'Simisear', 'Panpour',
       'Simipour', 'Munna', 'Musharna', 'Pidove', 'Tranquill', 'Unfezant',
       'Blitzle', 'Zebstrika', 'Roggenrola', 'Boldore', 'Gigalith',
       'Woobat', 'Swoobat', 'Drilbur', 'Excadrill', 'Audino',
       'AudinoMega Audino', 'Timburr', 'Gurdurr', 'Conkeldurr', 'Tympole',
       'Palpitoad', 'Seismitoad', 'Throh', 'Sawk', 'Sewaddle', 'Swadloon',
       'Leavanny', 'Venipede', 'Whirlipede', 'Scolipede', 'Cottonee',
       'Whimsicott', 'Petilil', 'Lilligant', 'Basculin', 'Sandile',
       'Krokorok', 'Krookodile', 'Darumaka', 'DarmanitanStandard Mode',
       'DarmanitanZen Mode', 'Maractus', 'Dwebble', 'Crustle', 'Scraggy',
       'Scrafty', 'Sigilyph', 'Yamask', 'Cofagrigus', 'Tirtouga',
       'Carracosta', 'Archen', 'Archeops', 'Trubbish', 'Garbodor',
       'Zorua', 'Zoroark', 'Minccino', 'Cinccino', 'Gothita', 'Gothorita',
       'Gothitelle', 'Solosis', 'Duosion', 'Reuniclus', 'Ducklett',
       'Swanna', 'Vanillite', 'Vanillish', 'Vanilluxe', 'Deerling',
       'Sawsbuck', 'Emolga', 'Karrablast', 'Escavalier', 'Foongus',
       'Amoonguss', 'Frillish', 'Jellicent', 'Alomomola', 'Joltik',
       'Galvantula', 'Ferroseed', 'Ferrothorn', 'Klink', 'Klang',
       'Klinklang', 'Tynamo', 'Eelektrik', 'Eelektross', 'Elgyem',
       'Beheeyem', 'Litwick', 'Lampent', 'Chandelure', 'Axew', 'Fraxure',
       'Haxorus', 'Cubchoo', 'Beartic', 'Cryogonal', 'Shelmet',
       'Accelgor', 'Stunfisk', 'Mienfoo', 'Mienshao', 'Druddigon',
       'Golett', 'Golurk', 'Pawniard', 'Bisharp', 'Bouffalant', 'Rufflet',
       'Braviary', 'Vullaby', 'Mandibuzz', 'Heatmor', 'Durant', 'Deino',
       'Zweilous', 'Hydreigon', 'Larvesta', 'Volcarona', 'Cobalion',
       'Terrakion', 'Virizion', 'TornadusIncarnate Forme',
       'TornadusTherian Forme', 'ThundurusIncarnate Forme',
       'ThundurusTherian Forme', 'Reshiram', 'Zekrom',
       'LandorusIncarnate Forme', 'LandorusTherian Forme', 'Kyurem',
       'KyuremBlack Kyurem', 'KyuremWhite Kyurem', 'KeldeoOrdinary Forme',
       'KeldeoResolute Forme', 'MeloettaAria Forme',
       'MeloettaPirouette Forme', 'Genesect', 'Chespin', 'Quilladin',
       'Chesnaught', 'Fennekin', 'Braixen', 'Delphox', 'Froakie',
       'Frogadier', 'Greninja', 'Bunnelby', 'Diggersby', 'Fletchling',
       'Fletchinder', 'Talonflame', 'Scatterbug', 'Spewpa', 'Vivillon',
       'Litleo', 'Pyroar', 'Flabébé', 'Floette', 'Florges', 'Skiddo',
       'Gogoat', 'Pancham', 'Pangoro', 'Furfrou', 'Espurr',
       'MeowsticMale', 'MeowsticFemale', 'Honedge', 'Doublade',
       'AegislashBlade Forme', 'AegislashShield Forme', 'Spritzee',
       'Aromatisse', 'Swirlix', 'Slurpuff', 'Inkay', 'Malamar', 'Binacle',
       'Barbaracle', 'Skrelp', 'Dragalge', 'Clauncher', 'Clawitzer',
       'Helioptile', 'Heliolisk', 'Tyrunt', 'Tyrantrum', 'Amaura',
       'Aurorus', 'Sylveon', 'Hawlucha', 'Dedenne', 'Carbink', 'Goomy',
       'Sliggoo', 'Goodra', 'Klefki', 'Phantump', 'Trevenant',
       'PumpkabooAverage Size', 'PumpkabooSmall Size',
       'PumpkabooLarge Size', 'PumpkabooSuper Size',
       'GourgeistAverage Size', 'GourgeistSmall Size',
       'GourgeistLarge Size', 'GourgeistSuper Size', 'Bergmite',
       'Avalugg', 'Noibat', 'Noivern', 'Xerneas', 'Yveltal',
       'Zygarde50% Forme', 'Diancie', 'DiancieMega Diancie',
       'HoopaHoopa Confined', 'HoopaHoopa Unbound', 'Volcanion'],
      dtype=object)

In [ ]:
to_replace = {
    'Type 1': 'Fairy',
    'Name': 'Ivysaur'
}
value = {
   'Type 1': 'FAIRY',
   'Name': 'IVYSAUR' 
}
replaced_df = df.replace(to_replace=to_replace, value=value)

In [ ]:
replaced_df['Type 1'].unique()

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'FAIRY', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

In [ ]:
replaced_df['Name'].unique()

array(['Bulbasaur', 'IVYSAUR', 'Venusaur', 'VenusaurMega Venusaur',
       'Charmander', 'Charmeleon', 'Charizard',
       'CharizardMega Charizard X', 'CharizardMega Charizard Y',
       'Squirtle', 'Wartortle', 'Blastoise', 'BlastoiseMega Blastoise',
       'Caterpie', 'Metapod', 'Butterfree', 'Weedle', 'Kakuna',
       'Beedrill', 'BeedrillMega Beedrill', 'Pidgey', 'Pidgeotto',
       'Pidgeot', 'PidgeotMega Pidgeot', 'Rattata', 'Raticate', 'Spearow',
       'Fearow', 'Ekans', 'Arbok', 'Pikachu', 'Raichu', 'Sandshrew',
       'Sandslash', 'Nidoran (Female)', 'Nidorina', 'Nidoqueen',
       'Nidoran (Male)', 'Nidorino', 'Nidoking', 'Clefairy', 'Clefable',
       'Vulpix', 'Ninetales', 'Jigglypuff', 'Wigglytuff', 'Zubat',
       'Golbat', 'Oddish', 'Gloom', 'Vileplume', 'Paras', 'Parasect',
       'Venonat', 'Venomoth', 'Diglett', 'Dugtrio', 'Meowth', 'Persian',
       'Psyduck', 'Golduck', 'Mankey', 'Primeape', 'Growlithe',
       'Arcanine', 'Poliwag', 'Poliwhirl', 'Poliwrath', 'Abra', 'Kadabra',
       'Alakazam', 'AlakazamMega Alakazam', 'Machop', 'Machoke',
       'Machamp', 'Bellsprout', 'Weepinbell', 'Victreebel', 'Tentacool',
       'Tentacruel', 'Geodude', 'Graveler', 'Golem', 'Ponyta', 'Rapidash',
       'Slowpoke', 'Slowbro', 'SlowbroMega Slowbro', 'Magnemite',
       'Magneton', "Farfetch'd", 'Doduo', 'Dodrio', 'Seel', 'Dewgong',
       'Grimer', 'Muk', 'Shellder', 'Cloyster', 'Gastly', 'Haunter',
       'Gengar', 'GengarMega Gengar', 'Onix', 'Drowzee', 'Hypno',
       'Krabby', 'Kingler', 'Voltorb', 'Electrode', 'Exeggcute',
       'Exeggutor', 'Cubone', 'Marowak', 'Hitmonlee', 'Hitmonchan',
       'Lickitung', 'Koffing', 'Weezing', 'Rhyhorn', 'Rhydon', 'Chansey',
       'Tangela', 'Kangaskhan', 'KangaskhanMega Kangaskhan', 'Horsea',
       'Seadra', 'Goldeen', 'Seaking', 'Staryu', 'Starmie', 'Mr. Mime',
       'Scyther', 'Jynx', 'Electabuzz', 'Magmar', 'Pinsir',
       'PinsirMega Pinsir', 'Tauros', 'Magikarp', 'Gyarados',
       'GyaradosMega Gyarados', 'Lapras', 'Ditto', 'Eevee', 'Vaporeon',
       'Jolteon', 'Flareon', 'Porygon', 'Omanyte', 'Omastar', 'Kabuto',
       'Kabutops', 'Aerodactyl', 'AerodactylMega Aerodactyl', 'Snorlax',
       'Articuno', 'Zapdos', 'Moltres', 'Dratini', 'Dragonair',
       'Dragonite', 'Mewtwo', 'MewtwoMega Mewtwo X',
       'MewtwoMega Mewtwo Y', 'Mew', 'Chikorita', 'Bayleef', 'Meganium',
       'Cyndaquil', 'Quilava', 'Typhlosion', 'Totodile', 'Croconaw',
       'Feraligatr', 'Sentret', 'Furret', 'Hoothoot', 'Noctowl', 'Ledyba',
       'Ledian', 'Spinarak', 'Ariados', 'Crobat', 'Chinchou', 'Lanturn',
       'Pichu', 'Cleffa', 'Igglybuff', 'Togepi', 'Togetic', 'Natu',
       'Xatu', 'Mareep', 'Flaaffy', 'Ampharos', 'AmpharosMega Ampharos',
       'Bellossom', 'Marill', 'Azumarill', 'Sudowoodo', 'Politoed',
       'Hoppip', 'Skiploom', 'Jumpluff', 'Aipom', 'Sunkern', 'Sunflora',
       'Yanma', 'Wooper', 'Quagsire', 'Espeon', 'Umbreon', 'Murkrow',
       'Slowking', 'Misdreavus', 'Unown', 'Wobbuffet', 'Girafarig',
       'Pineco', 'Forretress', 'Dunsparce', 'Gligar', 'Steelix',
       'SteelixMega Steelix', 'Snubbull', 'Granbull', 'Qwilfish',
       'Scizor', 'ScizorMega Scizor', 'Shuckle', 'Heracross',
       'HeracrossMega Heracross', 'Sneasel', 'Teddiursa', 'Ursaring',
       'Slugma', 'Magcargo', 'Swinub', 'Piloswine', 'Corsola', 'Remoraid',
       'Octillery', 'Delibird', 'Mantine', 'Skarmory', 'Houndour',
       'Houndoom', 'HoundoomMega Houndoom', 'Kingdra', 'Phanpy',
       'Donphan', 'Porygon2', 'Stantler', 'Smeargle', 'Tyrogue',
       'Hitmontop', 'Smoochum', 'Elekid', 'Magby', 'Miltank', 'Blissey',
       'Raikou', 'Entei', 'Suicune', 'Larvitar', 'Pupitar', 'Tyranitar',
       'TyranitarMega Tyranitar', 'Lugia', 'Ho-oh', 'Celebi', 'Treecko',
       'Grovyle', 'Sceptile', 'SceptileMega Sceptile', 'Torchic',
       'Combusken', 'Blaziken', 'BlazikenMega Blaziken', 'Mudkip',
       'Marshtomp', 'Swampert', 'SwampertMega Swampert', 'Poochyena',
       'Mightyena', 'Zigzagoon', 'Linoone', 'Wurmple', 'Silcoon',
       'Beautifly', 'Cascoon', 'Dustox', 'Lotad', 'Lombre', 'Ludicolo',
       'Seedot', 'Nuzleaf', 'Shiftry', 'Taillow', 'Swellow', 'Wingull',
       'Pelipper', 'Ralts', 'Kirlia', 'Gardevoir',
       'GardevoirMega Gardevoir', 'Surskit', 'Masquerain', 'Shroomish',
       'Breloom', 'Slakoth', 'Vigoroth', 'Slaking', 'Nincada', 'Ninjask',
       'Shedinja', 'Whismur', 'Loudred', 'Exploud', 'Makuhita',
       'Hariyama', 'Azurill', 'Nosepass', 'Skitty', 'Delcatty', 'Sableye',
       'SableyeMega Sableye', 'Mawile', 'MawileMega Mawile', 'Aron',
       'Lairon', 'Aggron', 'AggronMega Aggron', 'Meditite', 'Medicham',
       'MedichamMega Medicham', 'Electrike', 'Manectric',
       'ManectricMega Manectric', 'Plusle', 'Minun', 'Volbeat',
       'Illumise', 'Roselia', 'Gulpin', 'Swalot', 'Carvanha', 'Sharpedo',
       'SharpedoMega Sharpedo', 'Wailmer', 'Wailord', 'Numel', 'Camerupt',
       'CameruptMega Camerupt', 'Torkoal', 'Spoink', 'Grumpig', 'Spinda',
       'Trapinch', 'Vibrava', 'Flygon', 'Cacnea', 'Cacturne', 'Swablu',
       'Altaria', 'AltariaMega Altaria', 'Zangoose', 'Seviper',
       'Lunatone', 'Solrock', 'Barboach', 'Whiscash', 'Corphish',
       'Crawdaunt', 'Baltoy', 'Claydol', 'Lileep', 'Cradily', 'Anorith',
       'Armaldo', 'Feebas', 'Milotic', 'Castform', 'Kecleon', 'Shuppet',
       'Banette', 'BanetteMega Banette', 'Duskull', 'Dusclops', 'Tropius',
       'Chimecho', 'Absol', 'AbsolMega Absol', 'Wynaut', 'Snorunt',
       'Glalie', 'GlalieMega Glalie', 'Spheal', 'Sealeo', 'Walrein',
       'Clamperl', 'Huntail', 'Gorebyss', 'Relicanth', 'Luvdisc', 'Bagon',
       'Shelgon', 'Salamence', 'SalamenceMega Salamence', 'Beldum',
       'Metang', 'Metagross', 'MetagrossMega Metagross', 'Regirock',
       'Regice', 'Registeel', 'Latias', 'LatiasMega Latias', 'Latios',
       'LatiosMega Latios', 'Kyogre', 'KyogrePrimal Kyogre', 'Groudon',
       'GroudonPrimal Groudon', 'Rayquaza', 'RayquazaMega Rayquaza',
       'Jirachi', 'DeoxysNormal Forme', 'DeoxysAttack Forme',
       'DeoxysDefense Forme', 'DeoxysSpeed Forme', 'Turtwig', 'Grotle',
       'Torterra', 'Chimchar', 'Monferno', 'Infernape', 'Piplup',
       'Prinplup', 'Empoleon', 'Starly', 'Staravia', 'Staraptor',
       'Bidoof', 'Bibarel', 'Kricketot', 'Kricketune', 'Shinx', 'Luxio',
       'Luxray', 'Budew', 'Roserade', 'Cranidos', 'Rampardos', 'Shieldon',
       'Bastiodon', 'Burmy', 'WormadamPlant Cloak', 'WormadamSandy Cloak',
       'WormadamTrash Cloak', 'Mothim', 'Combee', 'Vespiquen',
       'Pachirisu', 'Buizel', 'Floatzel', 'Cherubi', 'Cherrim', 'Shellos',
       'Gastrodon', 'Ambipom', 'Drifloon', 'Drifblim', 'Buneary',
       'Lopunny', 'LopunnyMega Lopunny', 'Mismagius', 'Honchkrow',
       'Glameow', 'Purugly', 'Chingling', 'Stunky', 'Skuntank', 'Bronzor',
       'Bronzong', 'Bonsly', 'Mime Jr.', 'Happiny', 'Chatot', 'Spiritomb',
       'Gible', 'Gabite', 'Garchomp', 'GarchompMega Garchomp', 'Munchlax',
       'Riolu', 'Lucario', 'LucarioMega Lucario', 'Hippopotas',
       'Hippowdon', 'Skorupi', 'Drapion', 'Croagunk', 'Toxicroak',
       'Carnivine', 'Finneon', 'Lumineon', 'Mantyke', 'Snover',
       'Abomasnow', 'AbomasnowMega Abomasnow', 'Weavile', 'Magnezone',
       'Lickilicky', 'Rhyperior', 'Tangrowth', 'Electivire', 'Magmortar',
       'Togekiss', 'Yanmega', 'Leafeon', 'Glaceon', 'Gliscor',
       'Mamoswine', 'Porygon-Z', 'Gallade', 'GalladeMega Gallade',
       'Probopass', 'Dusknoir', 'Froslass', 'Rotom', 'RotomHeat Rotom',
       'RotomWash Rotom', 'RotomFrost Rotom', 'RotomFan Rotom',
       'RotomMow Rotom', 'Uxie', 'Mesprit', 'Azelf', 'Dialga', 'Palkia',
       'Heatran', 'Regigigas', 'GiratinaAltered Forme',
       'GiratinaOrigin Forme', 'Cresselia', 'Phione', 'Manaphy',
       'Darkrai', 'ShayminLand Forme', 'ShayminSky Forme', 'Arceus',
       'Victini', 'Snivy', 'Servine', 'Serperior', 'Tepig', 'Pignite',
       'Emboar', 'Oshawott', 'Dewott', 'Samurott', 'Patrat', 'Watchog',
       'Lillipup', 'Herdier', 'Stoutland', 'Purrloin', 'Liepard',
       'Pansage', 'Simisage', 'Pansear', 'Simisear', 'Panpour',
       'Simipour', 'Munna', 'Musharna', 'Pidove', 'Tranquill', 'Unfezant',
       'Blitzle', 'Zebstrika', 'Roggenrola', 'Boldore', 'Gigalith',
       'Woobat', 'Swoobat', 'Drilbur', 'Excadrill', 'Audino',
       'AudinoMega Audino', 'Timburr', 'Gurdurr', 'Conkeldurr', 'Tympole',
       'Palpitoad', 'Seismitoad', 'Throh', 'Sawk', 'Sewaddle', 'Swadloon',
       'Leavanny', 'Venipede', 'Whirlipede', 'Scolipede', 'Cottonee',
       'Whimsicott', 'Petilil', 'Lilligant', 'Basculin', 'Sandile',
       'Krokorok', 'Krookodile', 'Darumaka', 'DarmanitanStandard Mode',
       'DarmanitanZen Mode', 'Maractus', 'Dwebble', 'Crustle', 'Scraggy',
       'Scrafty', 'Sigilyph', 'Yamask', 'Cofagrigus', 'Tirtouga',
       'Carracosta', 'Archen', 'Archeops', 'Trubbish', 'Garbodor',
       'Zorua', 'Zoroark', 'Minccino', 'Cinccino', 'Gothita', 'Gothorita',
       'Gothitelle', 'Solosis', 'Duosion', 'Reuniclus', 'Ducklett',
       'Swanna', 'Vanillite', 'Vanillish', 'Vanilluxe', 'Deerling',
       'Sawsbuck', 'Emolga', 'Karrablast', 'Escavalier', 'Foongus',
       'Amoonguss', 'Frillish', 'Jellicent', 'Alomomola', 'Joltik',
       'Galvantula', 'Ferroseed', 'Ferrothorn', 'Klink', 'Klang',
       'Klinklang', 'Tynamo', 'Eelektrik', 'Eelektross', 'Elgyem',
       'Beheeyem', 'Litwick', 'Lampent', 'Chandelure', 'Axew', 'Fraxure',
       'Haxorus', 'Cubchoo', 'Beartic', 'Cryogonal', 'Shelmet',
       'Accelgor', 'Stunfisk', 'Mienfoo', 'Mienshao', 'Druddigon',
       'Golett', 'Golurk', 'Pawniard', 'Bisharp', 'Bouffalant', 'Rufflet',
       'Braviary', 'Vullaby', 'Mandibuzz', 'Heatmor', 'Durant', 'Deino',
       'Zweilous', 'Hydreigon', 'Larvesta', 'Volcarona', 'Cobalion',
       'Terrakion', 'Virizion', 'TornadusIncarnate Forme',
       'TornadusTherian Forme', 'ThundurusIncarnate Forme',
       'ThundurusTherian Forme', 'Reshiram', 'Zekrom',
       'LandorusIncarnate Forme', 'LandorusTherian Forme', 'Kyurem',
       'KyuremBlack Kyurem', 'KyuremWhite Kyurem', 'KeldeoOrdinary Forme',
       'KeldeoResolute Forme', 'MeloettaAria Forme',
       'MeloettaPirouette Forme', 'Genesect', 'Chespin', 'Quilladin',
       'Chesnaught', 'Fennekin', 'Braixen', 'Delphox', 'Froakie',
       'Frogadier', 'Greninja', 'Bunnelby', 'Diggersby', 'Fletchling',
       'Fletchinder', 'Talonflame', 'Scatterbug', 'Spewpa', 'Vivillon',
       'Litleo', 'Pyroar', 'Flabébé', 'Floette', 'Florges', 'Skiddo',
       'Gogoat', 'Pancham', 'Pangoro', 'Furfrou', 'Espurr',
       'MeowsticMale', 'MeowsticFemale', 'Honedge', 'Doublade',
       'AegislashBlade Forme', 'AegislashShield Forme', 'Spritzee',
       'Aromatisse', 'Swirlix', 'Slurpuff', 'Inkay', 'Malamar', 'Binacle',
       'Barbaracle', 'Skrelp', 'Dragalge', 'Clauncher', 'Clawitzer',
       'Helioptile', 'Heliolisk', 'Tyrunt', 'Tyrantrum', 'Amaura',
       'Aurorus', 'Sylveon', 'Hawlucha', 'Dedenne', 'Carbink', 'Goomy',
       'Sliggoo', 'Goodra', 'Klefki', 'Phantump', 'Trevenant',
       'PumpkabooAverage Size', 'PumpkabooSmall Size',
       'PumpkabooLarge Size', 'PumpkabooSuper Size',
       'GourgeistAverage Size', 'GourgeistSmall Size',
       'GourgeistLarge Size', 'GourgeistSuper Size', 'Bergmite',
       'Avalugg', 'Noibat', 'Noivern', 'Xerneas', 'Yveltal',
       'Zygarde50% Forme', 'Diancie', 'DiancieMega Diancie',
       'HoopaHoopa Confined', 'HoopaHoopa Unbound', 'Volcanion'],
      dtype=object)

## Export dataframe to desired format

In [ ]:
df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']

In [ ]:
df.head()

### To csv files

In [ ]:
df.to_csv('Modified.csv', index=False)

### To excel files

In [ ]:
df.to_excel('Modifiled.xlsx', index=False)

### To text files

In [ ]:
df.to_csv('Modified.txt', index=False, sep='\t')

## Filter data

### Filter columns by conditions

In [ ]:
df[df['Type 1'] == 'Grass']

       #                   Name Type 1  ... Generation  Legendary  Total
0      1              Bulbasaur  Grass  ...          1      False    318
1      2                Ivysaur  Grass  ...          1      False    405
2      3               Venusaur  Grass  ...          1      False    525
3      3  VenusaurMega Venusaur  Grass  ...          1      False    625
48    43                 Oddish  Grass  ...          1      False    320
..   ...                    ...    ...  ...        ...        ...    ...
718  650                Chespin  Grass  ...          6      False    313
719  651              Quilladin  Grass  ...          6      False    405
720  652             Chesnaught  Grass  ...          6      False    530
740  672                 Skiddo  Grass  ...          6      False    350
741  673                 Gogoat  Grass  ...          6      False    531

[70 rows x 13 columns]

In [ ]:
df[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison') & (df['HP'] > 50)]

       #                   Name Type 1  ... Generation  Legendary  Total
1      2                Ivysaur  Grass  ...          1      False    405
2      3               Venusaur  Grass  ...          1      False    525
3      3  VenusaurMega Venusaur  Grass  ...          1      False    625
49    44                  Gloom  Grass  ...          1      False    395
50    45              Vileplume  Grass  ...          1      False    490
76    70             Weepinbell  Grass  ...          1      False    390
77    71             Victreebel  Grass  ...          1      False    490
452  407               Roserade  Grass  ...          4      False    515
651  590                Foongus  Grass  ...          5      False    294
652  591              Amoonguss  Grass  ...          5      False    464

[10 rows x 13 columns]

### Reset index

In [ ]:
filtered_df = df[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison') & (df['HP'] > 50)]

In [ ]:
filtered_df

       #                   Name Type 1  ... Generation  Legendary  Total
1      2                Ivysaur  Grass  ...          1      False    405
2      3               Venusaur  Grass  ...          1      False    525
3      3  VenusaurMega Venusaur  Grass  ...          1      False    625
49    44                  Gloom  Grass  ...          1      False    395
50    45              Vileplume  Grass  ...          1      False    490
76    70             Weepinbell  Grass  ...          1      False    390
77    71             Victreebel  Grass  ...          1      False    490
452  407               Roserade  Grass  ...          4      False    515
651  590                Foongus  Grass  ...          5      False    294
652  591              Amoonguss  Grass  ...          5      False    464

[10 rows x 13 columns]

In [ ]:
filtered_df.iloc[0]

In [ ]:
filtered_df.reset_index(drop=True, inplace=True)

In [ ]:
filtered_df

     #                   Name Type 1  ... Generation  Legendary  Total
0    2                Ivysaur  Grass  ...          1      False    405
1    3               Venusaur  Grass  ...          1      False    525
2    3  VenusaurMega Venusaur  Grass  ...          1      False    625
3   44                  Gloom  Grass  ...          1      False    395
4   45              Vileplume  Grass  ...          1      False    490
5   70             Weepinbell  Grass  ...          1      False    390
6   71             Victreebel  Grass  ...          1      False    490
7  407               Roserade  Grass  ...          4      False    515
8  590                Foongus  Grass  ...          5      False    294
9  591              Amoonguss  Grass  ...          5      False    464

[10 rows x 13 columns]

### Filter rows that contain a specific value

In [ ]:
df[df['Name'].str.contains('Mega')]

       #                       Name    Type 1  ... Generation  Legendary  Total
3      3      VenusaurMega Venusaur     Grass  ...          1      False    625
7      6  CharizardMega Charizard X      Fire  ...          1      False    634
8      6  CharizardMega Charizard Y      Fire  ...          1      False    634
12     9    BlastoiseMega Blastoise     Water  ...          1      False    630
19    15      BeedrillMega Beedrill       Bug  ...          1      False    495
23    18        PidgeotMega Pidgeot    Normal  ...          1      False    579
71    65      AlakazamMega Alakazam   Psychic  ...          1      False    590
87    80        SlowbroMega Slowbro     Water  ...          1      False    590
102   94          GengarMega Gengar     Ghost  ...          1      False    600
124  115  KangaskhanMega Kangaskhan    Normal  ...          1      False    590
137  127          PinsirMega Pinsir       Bug  ...          1      False    600
141  130      GyaradosMega Gyarados     Water  ...          1      False    640
154  142  AerodactylMega Aerodactyl      Rock  ...          1      False    615
163  150        MewtwoMega Mewtwo X   Psychic  ...          1       True    780
164  150        MewtwoMega Mewtwo Y   Psychic  ...          1       True    780
168  154                   Meganium     Grass  ...          2      False    525
196  181      AmpharosMega Ampharos  Electric  ...          2      False    610
224  208        SteelixMega Steelix     Steel  ...          2      False    610
229  212          ScizorMega Scizor       Bug  ...          2      False    600
232  214    HeracrossMega Heracross       Bug  ...          2      False    600
248  229      HoundoomMega Houndoom      Dark  ...          2      False    600
268  248    TyranitarMega Tyranitar      Rock  ...          2      False    700
275  254      SceptileMega Sceptile     Grass  ...          3      False    630
279  257      BlazikenMega Blaziken      Fire  ...          3      False    630
283  260      SwampertMega Swampert     Water  ...          3      False    635
306  282    GardevoirMega Gardevoir   Psychic  ...          3      False    618
327  302        SableyeMega Sableye      Dark  ...          3      False    480
329  303          MawileMega Mawile     Steel  ...          3      False    480
333  306          AggronMega Aggron     Steel  ...          3      False    630
336  308      MedichamMega Medicham  Fighting  ...          3      False    510
339  310    ManectricMega Manectric  Electric  ...          3      False    575
349  319      SharpedoMega Sharpedo     Water  ...          3      False    560
354  323      CameruptMega Camerupt      Fire  ...          3      False    560
366  334        AltariaMega Altaria    Dragon  ...          3      False    590
387  354        BanetteMega Banette     Ghost  ...          3      False    555
393  359            AbsolMega Absol      Dark  ...          3      False    565
397  362          GlalieMega Glalie       Ice  ...          3      False    580
409  373    SalamenceMega Salamence    Dragon  ...          3      False    700
413  376    MetagrossMega Metagross     Steel  ...          3      False    700
418  380          LatiasMega Latias    Dragon  ...          3       True    700
420  381          LatiosMega Latios    Dragon  ...          3       True    700
426  384      RayquazaMega Rayquaza    Dragon  ...          3       True    780
476  428        LopunnyMega Lopunny    Normal  ...          4      False    580
494  445      GarchompMega Garchomp    Dragon  ...          4      False    700
498  448        LucarioMega Lucario  Fighting  ...          4      False    625
511  460    AbomasnowMega Abomasnow     Grass  ...          4      False    594
527  475        GalladeMega Gallade   Psychic  ...          4      False    618
591  531          AudinoMega Audino    Normal  ...          5      False    545
796  719        DiancieMega Diancie      Rock  ...          6       True    700

[49 rows x 13 columns]

In [ ]:
df['Name'].str.contains('Mega')

### Filter rows NOT contain a specific value

In [ ]:
df[~df['Name'].str.contains('Mega')]

       #                 Name   Type 1  ... Generation  Legendary  Total
0      1            Bulbasaur    Grass  ...          1      False    318
1      2              Ivysaur    Grass  ...          1      False    405
2      3             Venusaur    Grass  ...          1      False    525
4      4           Charmander     Fire  ...          1      False    309
5      5           Charmeleon     Fire  ...          1      False    405
..   ...                  ...      ...  ...        ...        ...    ...
794  718     Zygarde50% Forme   Dragon  ...          6       True    600
795  719              Diancie     Rock  ...          6       True    600
797  720  HoopaHoopa Confined  Psychic  ...          6       True    600
798  720   HoopaHoopa Unbound  Psychic  ...          6       True    680
799  721            Volcanion     Fire  ...          6       True    600

[751 rows x 13 columns]

## Aggregate Statistics (Groupby)

In [ ]:
df.groupby(by='Type 1').mean()

                   #         HP      Attack  ...  Generation  Legendary       Total
Type 1                                       ...
Bug       334.492754  56.884058   70.971014  ...    3.217391   0.000000  378.927536
Dark      461.354839  66.806452   88.387097  ...    4.032258   0.064516  445.741935
Dragon    474.375000  83.312500  112.125000  ...    3.875000   0.375000  550.531250
Electric  363.500000  59.795455   69.090909  ...    3.272727   0.090909  443.409091
Fairy     449.529412  74.117647   61.529412  ...    4.117647   0.058824  413.176471
Fighting  363.851852  69.851852   96.777778  ...    3.370370   0.000000  416.444444
Fire      327.403846  69.903846   84.769231  ...    3.211538   0.096154  458.076923
Flying    677.750000  70.750000   78.750000  ...    5.500000   0.500000  485.000000
Ghost     486.500000  64.437500   73.781250  ...    4.187500   0.062500  439.562500
Grass     344.871429  67.271429   73.214286  ...    3.357143   0.042857  421.142857
Ground    356.281250  73.781250   95.750000  ...    3.156250   0.125000  437.500000
Ice       423.541667  72.000000   72.750000  ...    3.541667   0.083333  433.458333
Normal    319.173469  77.275510   73.469388  ...    3.051020   0.020408  401.683673
Poison    251.785714  67.250000   74.678571  ...    2.535714   0.000000  399.142857
Psychic   380.807018  70.631579   71.456140  ...    3.385965   0.245614  475.947368
Rock      392.727273  65.363636   92.863636  ...    3.454545   0.090909  453.750000
Steel     442.851852  65.222222   92.703704  ...    3.851852   0.148148  487.703704
Water     303.089286  72.062500   74.151786  ...    2.857143   0.035714  430.455357

[18 rows x 10 columns]

In [ ]:
df.groupby(by=['Type 1', 'Type 2']).count()

                  #  Name  HP  Attack  ...  Speed  Generation  Legendary  Total
Type 1 Type 2                          ...
Bug    Electric   2     2   2       2  ...      2           2          2      2
       Fighting   2     2   2       2  ...      2           2          2      2
       Fire       2     2   2       2  ...      2           2          2      2
       Flying    14    14  14      14  ...     14          14         14     14
       Ghost      1     1   1       1  ...      1           1          1      1
...              ..   ...  ..     ...  ...    ...         ...        ...    ...
Water  Ice        3     3   3       3  ...      3           3          3      3
       Poison     3     3   3       3  ...      3           3          3      3
       Psychic    5     5   5       5  ...      5           5          5      5
       Rock       4     4   4       4  ...      4           4          4      4
       Steel      1     1   1       1  ...      1           1          1      1

[136 rows x 11 columns]