# <center>Decision Trees</center>

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
%cd '/content/drive/MyDrive/Reskill/fml/Classification'

/content/drive/MyDrive/Reskill/fml/Classification

Import the Following Libraries:
<ul>
    <li> <b>numpy (as np)</b> </li>
    <li> <b>pandas</b> </li>
    <li> <b>DecisionTreeClassifier</b> from <b>sklearn.tree</b> </li>
</ul>

In [7]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

now, read data using pandas dataframe:

In [8]:
# Your code here
my_data = pd.read_csv('ChurnData.csv')
my_data.head()

   tenure   age  address  income   ed  ...  loglong  logtoll  lninc  custcat  churn
0    11.0  33.0      7.0   136.0  5.0  ...    1.482    3.033  4.913      4.0    1.0
1    33.0  33.0     12.0    33.0  2.0  ...    2.246    3.240  3.497      1.0    1.0
2    23.0  30.0      9.0    30.0  1.0  ...    1.841    3.240  3.401      3.0    0.0
3    38.0  35.0      5.0    76.0  2.0  ...    1.800    3.807  4.331      4.0    0.0
4     7.0  35.0     14.0    80.0  2.0  ...    1.960    3.091  4.382      3.0    0.0

[5 rows x 28 columns]

In [9]:
col_corr = my_data.corr()['churn']

In [10]:
colums = abs(col_corr ) > 0.2

In [11]:
col = my_data.columns[colums]

In [12]:
data = my_data[col]
data.head()

   tenure   age  address   ed  employ  ...  cardten  internet  ebill  loglong  churn
0    11.0  33.0      7.0  5.0     5.0  ...    125.0       0.0    0.0    1.482    1.0
1    33.0  33.0     12.0  2.0     0.0  ...      0.0       0.0    0.0    2.246    1.0
2    23.0  30.0      9.0  1.0     2.0  ...      0.0       0.0    0.0    1.841    0.0
3    38.0  35.0      5.0  2.0    10.0  ...    880.0       1.0    1.0    1.800    0.0
4     7.0  35.0     14.0  2.0    15.0  ...    145.0       0.0    0.0    1.960    0.0

[5 rows x 15 columns]

## Practice 
What is the size of data?

In [13]:
# write your code here
my_data.shape

(200, 28)

## Pre-processing

Using <b>my_data</b> as the play.csv data read by pandas, declare the following variables: <br>

<ul>
    <li> <b> X </b> as the <b> Feature Matrix </b> (data of my_data) </li>
    <li> <b> y </b> as the <b> response vector (target) </b> </li>
</ul>

Remove the column containing the target name since it doesn't contain numeric values.

In [14]:
X = my_data[['outlook','temperature','humidity','wind']].values
X[0:5]

KeyError: ignored

In [ ]:
type(X)

In [ ]:
print(np.unique(X[:,1]))
print(np.unique(X[:,2]))
print(np.unique(X[:,3]))

As you may figure out, some features in this dataset are categorical such as __Windy__ or __Outlook__. Unfortunately, Sklearn Decision Trees do not handle categorical variables. But still we can convert these features to numerical values. __pandas.get_dummies()__
Convert categorical variable into dummy/indicator variables.

In [ ]:
from sklearn import preprocessing
le_windy = preprocessing.LabelEncoder()

In [ ]:
X = my_data.drop('play', axis=1).apply(preprocessing.LabelEncoder().fit_transform)
X.shape

Now we can fill the target variable.

In [ ]:
y = my_data["play"]
y.shape

---
## Setting up the Decision Tree
We will be using <b>train/test split</b> on our <b>decision tree</b>. Let's import <b>train_test_split</b> from <b>sklearn.cross_validation</b>.

In [ ]:
from sklearn.model_selection import train_test_split

Now <b> train_test_split </b> will return 4 different parameters. We will name them:<br>
X_trainset, X_testset, y_trainset, y_testset <br> <br>
The <b> train_test_split </b> will need the parameters: <br>
X, y, test_size=0.3, and random_state=3. <br> <br>
The <b>X</b> and <b>y</b> are the arrays required before the split, the <b>test_size</b> represents the ratio of the testing dataset, and the <b>random_state</b> ensures that we obtain the same splits.

In [ ]:
X_trainset, X_testset, y_trainset, y_testset = train_test_split(X, y, test_size=0.3, random_state=3)

## Practice
Print the shape of X_trainset and y_trainset. Ensure that the dimensions match

In [ ]:
# your code
print(X_trainset.shape)
print(y_trainset.shape)

Print the shape of X_testset and y_testset. Ensure that the dimensions match

In [ ]:
# your code
print(X_testset.shape)
print(y_testset.shape)

## Modeling
We will first create an instance of the <b>DecisionTreeClassifier</b> called <b>drugTree</b>.<br>
Inside of the classifier, specify <i> criterion="entropy" </i> so we can see the information gain of each node.

In [ ]:
clf = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
clf # it shows the default parameters

Next, we will fit the data with the training feature matrix <b> X_trainset </b> and training  response vector <b> y_trainset </b>

In [ ]:
clf.fit(X_trainset,y_trainset)

In [ ]:
from sklearn import tree
tree.plot_tree(clf)

## Prediction
Let's make some <b>predictions</b> on the testing dataset and store it into a variable called <b>predTree</b>.

In [ ]:
predTree = clf.predict(X_testset)

You can print out <b>predTree</b> and <b>y_testset</b> if you want to visually compare the prediction to the actual values.

In [ ]:
print (predTree [0:5])
print (y_testset [0:5])

## Evaluation
Next, let's import __metrics__ from sklearn and check the accuracy of our model.

In [ ]:
from sklearn import metrics
import matplotlib.pyplot as plt
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_testset, predTree))

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100, max_depth=5,random_state=0)
clf.fit(X_trainset, y_trainset)  
print(my_data.columns[0:5])
print(clf.feature_importances_)

In [ ]:
pred = clf.predict(X_testset)
print("Random Forest's Accuracy: ", metrics.accuracy_score(y_testset, pred))

__Accuracy classification score__ computes subset accuracy: the set of labels predicted for a sample must exactly match the corresponding set of labels in y_true.  

In multilabel classification, the function returns the subset accuracy. If the entire set of predicted labels for a sample strictly match with the true set of labels, then the subset accuracy is 1.0; otherwise it is 0.0.

# Save model

In [ ]:
import pickle
# save the model to disk
filename = 'finalized_model.sav'
pickle.dump(clf, open(filename, 'wb'))

# Load model and predict

In [ ]:
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
pred = loaded_model.predict(X_testset)
print(pred)